cloud:
  aws:
    credentials:
      access-key: AKIA2HDIMUN776Z3S45T
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: awscbucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 5000

